### ISSUE TITLE
Use gst-device-monitor to improve format detection in camera gstreamer basic  

### ISSUE THREAD

**Issue by PIERROOOTT** [LaboratoireMecaniqueLille/crappy#58]
Even after the improvements in #55, the available formats for the [`CameraGstreamer`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/bc0c43cca3ec3499b2ac2d6687c01fe6dbd28070/src/crappy/camera/gstreamer_camera_basic.py) Camera are guessed when `v4l2-ctl` is not installed. This is of course not the most desirable behavior, as the guessed formats could be wrong and there could be missing formats.

Using the command `gst-device-monitor-1.0 Video/Source`, the available formats can be listed, at least on Linux. It should be tested whether this behavior is also available on Windows and macOS. It should also be checked how to set the format using only the commands of GStreamer.

### ToDo

- [x] Check the availability of `gst-device-monitor-1.0 Video/Source` on Windows and macOS
- [x] Check how to set a format using only the GStreamer commands
- [x] Implement parsing of the format string and add the format selection as an available setting
