### ISSUE TITLE
Better parsing of v4l2-ctl output in CameraOpencv

### ISSUE THREAD

**Issue by WeisLeDocto** [LaboratoireMecaniqueLille/crappy#65]
Recently, #55 added a better parsing of [`v4l2-ctl`](https://manpages.ubuntu.com/manpages/focal/man1/v4l2-ctl.1.html)'s output on Linux machines for the [`CameraGstreamer`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/bc0c43cca3ec3499b2ac2d6687c01fe6dbd28070/src/crappy/camera/gstreamer_camera_v4l2.py) Camera object. In particular, it allowed to automatically add to the configuration window all the parameters listed by `v4l2-ctl`, with a correct handling of their type, value, limits, etc.

As [`CameraOpencv`](https://github.com/LaboratoireMecaniqueLille/crappy/blob/bc0c43cca3ec3499b2ac2d6687c01fe6dbd28070/src/crappy/camera/opencv_camera.py) also relies on `v4l2-ctl` for determining the available settings of the driven camera on Linux machines, a similar improvement should be brought to this second class. The possibility to tune the settings directly with `v4l2-ctl` instead of OpenCV should be explored.

In case `CameraGstreamer` and `CameraOpencv` would end up being extremely similar on Linux machines, having them both derived from a common parent class would be nice.
On Windows and macOS, the `CameraGstreamer` and `CameraOpencv` will likely remain very limited, unless we find an equivalent to `v4l2-ctl`.

This issue contains #17.

### ToDo

- [x] Split the `CameraOpencv` class in two, one class for Linux using `v4l2-ctl` and the other for other situations
- [x] In the class that uses `v4l2-ctl`, apply the same parsing as in `CameraGstreamer`
- [x] If possible, use `v4l2-ctl` directly for tuning settings instead of relying on OpenCV
- [x] If applicable, create a parent class for both `CameraGstreamer` and `CameraOpencv` that handles parsing of `v4l2-ctl`
